### ISSUE TITLE
Project is not open source without a license file

### ISSUE THREAD

**Issue by karan** [phuein/Tunebot#2]
Without a license, this project isn't open source and no one can use the code.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

**Comment by phuein** [comment]
A work of code without license is public, is it not?

I reckon I have to explicitly set a limiting license, in order to legally prevent anyone from using my code. Otherwise, by default, it is public.

**Comment by notnola** [comment]
Generally speaking the absence of a license means that default copyright laws apply.
