### ISSUE TITLE
Call to function privmsg failed

### ISSUE THREAD

**Issue by cnvo** [phuein/Tunebot#2]
Got this strange error while connected in a room. It (the bot) doesn't join the room all the way properly.

`[23.57.55][1][roomname] [{'code': u'NetConnection.Call.Failed', 'description': u'call to function privmsg failed', 'level': u'error'}]`

**Comment by phuein** [comment]
This error means it can't do privmsg(), obviously, which normally means that bot has not passed Recaptcha. Maybe also regular chat captcha, if applicable, can't recall.

I could/should probably beautify the error, but meh.

**Comment by cnvo** [comment]
Meh, perhaps, but very low priority I suppose. And this was somehow fixed on master.
