### ISSUE TITLE
Vote Ban/Kick (Feature)

### ISSUE THREAD

**Issue by cnvo** [phuein/Tunebot#3]
I remember this from an older version notnola had created. It worked but had no type of protection from spamming from users that had no account. Now that Tinychat has implemented a one account per IP login method, this would actually work if the bot recognizes users with actual accounts.

**Comment by phuein** [comment]
The latest version of the bot recognizes both botters and modders by account. However, I've never liked the vote commands. Democracy is a lie. :P If you need more bans, get more mods. Botters are, by rule, after two years of doing this, very unreliable.

**Comment by cnvo** [comment]
The vote commands were sustainable, and we have more than enough mods. There could be an option to activate/deactivate this particular feature. **Power to the people...**

**Comment by TechWhizZ199** [comment]
To be honest, it was a decent command, apart from banning, the voting functions could be used for polling and video choices etc. 

If James doesn't add it, you could just try yourself, use the code Nola did and modify it or instead make your own with a bit of thinking.

**Comment by phuein** [comment]
Well, I'm not interested, BUT if you do add it properly to the code, then I am happy to merge it into master. :) But do try to follow the same style of the code. Otherwise shit will start looking like soup, eh.

**Comment by TechWhizZ199** [comment]
Right, I might add it to mine then see how yours is done and then see what I can forge.

**Comment by phuein** [comment]
If you're going to make a voting system, might as well abstract its parts enough, so it can be used for any kind of voting, eh. :D Not only bans.

**Comment by TechWhizZ199** [comment]
Yeah I was thinking along the same, lines, banning, rating, videos etc.
